### ISSUE TITLE
local date fformat overwritten when syncing from calendar

### ISSUE THREAD

**Issue by itluzanky** [Davepar/gcalendarsync#77] opened 2020-09-16 22:28 UTC
When I sync from calendar, local date format is overwritten by US standard.

Before sync:
![image](https://user-images.githubusercontent.com/69956743/93398456-e97a6580-f87b-11ea-8612-c1ee26c9b02a.png)

And, moreover and more importantly, it shifts some dates:
After ("Update from calendar"):
![image](https://user-images.githubusercontent.com/69956743/93398669-4e35c000-f87c-11ea-9fa3-a9a7abc7f354.png)

(the sheet is here https://docs.google.com/spreadsheets/d/1HvsaNjmquyga7ruJmEEPOLrPhbY8b4vRRFu99OdSxgw/edit#gid=901722093 )

The bug with shifting dates would be easily fixed by not requiring END TIME (as stated in manual) (issue #73)

**Comment by Davepar** [comment] 2020-09-18 23:49
Ah, thanks for pointing this out. This was caused by an earlier attempt to fix the off-by-one issue. Should be fixed now.

The end date would still be needed for multi-day events, so the off by one error would happen in that case. Sorry I haven't made the end date optional yet. It's more work than it sounds.

**Closed by Davepar** 2020-09-18 23:49 UTC

**Comment by itluzanky** [comment] 2020-09-21 08:31
I've just tested this, and it seems to be OK now, thanks!
